### ISSUE TITLE
chr() arg not in range(0x110000)

### ISSUE THREAD

**Issue by szczynk** [frosenek/ro-bot#1]
hello, i'm getting this error while succesfully run the code
here some log

_Traceback (most recent call last):
  File "C:\Users\\+++++\Desktop\New folder\ro-bot-master\main.py", line 27, in <module>
    robot = Robot(app, 'UnRo | Gepard Shield 3.0 (^-_-^)','UnRo.exe')
  File "C:\Users\\+++++\Desktop\New folder\ro-bot-master\robot.py", line 35, in __init__
    self.read_game_state()
  File "C:\Users\\+++++\Desktop\New folder\ro-bot-master\robot.py", line 98, in read_game_state
    self.game.read()
  File "C:\Users\\+++++\Desktop\New folder\ro-bot-master\model\game.py", line 128, in read
    self.read_map()
  File "C:\Users\\+++++\Desktop\New folder\ro-bot-master\model\game.py", line 199, in read_map
    c = chr(self.memory.read_byte(mapname_addr))
ValueError: chr() arg not in range(0x110000)_

after i check 
`base = 0x400000`
`mapname_addr = base + 0x62AA18`
`mapname_addr = 10660376`
`memory.read_byte(mapname_addr) = -117 `
which less then 0 which create this chr() error

how to fix it?
thank you

**Comment by souryuu** [comment]
I also stuck at read_map(). 
In my case, `self.memory.read_byte(mapname_addr)` always return 0 and the while loop never break.
```
        while True:
            c = chr(self.memory.read_byte(mapname_addr))
            if c == '.':
                break
            mapname = mapname + c
            mapname_addr = mapname_addr + 1
```

**Comment by aninostephen** [comment]
> I also stuck at read_map(). In my case, `self.memory.read_byte(mapname_addr)` always return 0 and the while loop never break.
> 
> ```
>         while True:
>             c = chr(self.memory.read_byte(mapname_addr))
>             if c == '.':
>                 break
>             mapname = mapname + c
>             mapname_addr = mapname_addr + 1
> ```

Encounter also this. i guess it was a game wrong base address

**Comment by frosenek** [comment]
The memory addresses i worked out back then are likely not valid with newer client versions.
You would have to adjust them accordingly.
