### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by intheone1** [frosenek/ro-bot#2]
hello, i'm getting this error while succesfully run the code
here some log

Traceback (most recent call last):
  File "main.py", line 27, in <module>
    robot = Robot(app, 'Ragnarok', 'Ragexe.exe')
  File "C:\ro-bot-master\robot.py", line 25, in __init__
    self.scr_2 = self.app.screens()[1].availableGeometry()
IndexError: list index out of range

how to fix it?

thanks you :)

**Comment by szczynk** [comment]
i've tried using second screen and it worked but it come back to the 1st issue that I posted
